language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update;
      sudo apt-get install -y glide;
    fi

install:
  - make vendor
  - export GO15VENDOREXPERIMENT=1

before_script:
  - if [[ "$(go version)" =~ "go version go1.5" ]]; then echo skipping gometalinter; else make lint-prepare; fi

script:
  - if [[ "$(go version)" =~ "go version go1.5" ]]; then echo skipping gometalinter; else make lint; fi
  - make test
