language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - make vendor-prepare

install:
  - make vendor

before_script:
  - make vendor-lint

script:
  - make lint
  - make test
