language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

os:
  - linux
  - osx

before_install:
  make vendor-prepare

install:
  - make vendor
  # - if [[ "$(go version)" =~ "go version go1.5" ]]; then export GO15VENDOREXPERIMENT=1; fi

before_script:
  # - if [[ "$(go version)" =~ "go version go1.5" ]]; then echo skipping gometalinter; else make lint-prepare; fi

script:
  # - if [[ "$(go version)" =~ "go version go1.5" ]]; then echo skipping gometalinter; else make lint; fi
  - make test
